blank_issues_enabled: false
contact_links: 
  - name: "Youtube"
    url: youtube.com/@infoyps
    about: My Youtube Channel
  - name: "GitHub"
    url: github.com/PSGitHubUser1
    about: My github page
  - name: "Discord Server"
    url: https://discord.gg/GYATqrtJSq
    about: My Discord Server
  - name: "Personal Discord"
    about: PSPlaysMC#3778
